### PR TITLE
Auto-creates a release when master branch is updated

### PR DESCRIPTION
**Pull request by ghost**
### Feature: build-and-release Workflow

This pull request includes a [github action](https://github.com/R-Y-M-R/webhookly/actions) (and requirements for said action) which tries to [tag and Release a .jar](https://github.com/R-Y-M-R/webhookly/releases/tag/v1) automatically when new code is pushed to the ``master`` branch.  This will allow users to download the latest .jar file directly and use it as a library if they want. This also addresses #5 as instead of waiting for a response from jitpack, they can use a local .jar.

**Added requirements:**
- fatJar gradle task
- gradle wrapper

**Testing**
- I tested adding the .jar as a library to a project and using the webhooks. It seemed to work fine.

### CODE REVIEW

**Comment by micartey** [comment]
Using local jars is bad practice and you only need to wait for it once, as it will be cached after download.

On that note: The reason for my decline is the malicious gradle wrapper you neatly tried to include.
Sadly for you, I purpose this a when we had a red team exercise and tried to simulate an attack on another open source project.

**Comment by micartey** [comment]
For transparency:
The `Install.class` doesn't normally look like this:

```java
public final class Install {
    public final Logger logger;
    public final Download download;
    public final ExclusiveFileAccessManager exclusiveFileAccessManager;

    public Install(Logger logger, Download download, PathAssembler pathAssembler) {
        ExclusiveFileAccessManager exclusiveFileAccessManager;
        ExclusiveFileAccessManager exclusiveFileAccessManager2 = exclusiveFileAccessManager;
        exclusiveFileAccessManager = new ExclusiveFileAccessManager();
        v1.exclusiveFileAccessManager = exclusiveFileAccessManager2;
        v1.logger = logger;
        v1.download = download;
    }

    /*
     * Could not resolve type clashes
     * Unable to fully structure code
     */
    public static Install$InstallCheck access$000(Install var0, File var1_1, String var2_2) {
        block8: {
            block9: {
                block7: {
                    var0.getClass();
                    if (!var1_1 /* !! */ .exists() || (var0 = var1_1 /* !! */ .listFiles()) == null) {
                        var0 = Collections.emptyList();
                    } else {
                        var1_1 /* !! */  = v0;
                        v0 = new ArrayList<E>();
                        for (Object var5_5 : var0) {
                            if (!var5_5.isDirectory()) continue;
                            var1_1 /* !! */ .add(var5_5);
                        }
                        var0 = var1_1 /* !! */ ;
                    }
                    if (!var0.isEmpty()) break block7;
                    v1 = new Object[1];
                    var0 = v1;
                    v1[0] = var2_2;
                    var0 = String.format("Gradle distribution '%s' does not contain any directories. Expected to find exactly 1 directory.", var0);
                    var1_1 /* !! */  = v2;
                    v2 = new Install$InstallCheck(null, (String)var0);
                    break block8;
                }
                if (var0.size() == 1) break block9;
                v3 = new Object[1];
                var0 = v3;
                v3[0] = var2_2;
                var0 = String.format("Gradle distribution '%s' contains too many directories. Expected to find exactly 1 directory.", var0);
                var1_1 /* !! */  = v4;
                v4 = new Install$InstallCheck(null, (String)var0);
                break block8;
            }
            var0 = (File)var0.get(0);
            var1_1 /* !! */  = v5;
            if (!new File((File)var0, "lib").exists() || !var1_1 /* !! */ .isDirectory()) ** GOTO lbl-1000
            v6 = var1_1 /* !! */ ;
            var1_1 /* !! */  = v7;
            v7 = new BootstrapMainStarter$1();
            if ((var1_1 /* !! */  = v6.listFiles((FilenameFilter)var1_1 /* !! */ )) != null && var1_1 /* !! */ .length == 1) {
                v8 = var1_1 /* !! */ [0];
            } else lbl-1000:
            // 2 sources

            {
                v8 = null;
            }
            if (v8 == null) {
                v9 = new Object[1];
                var0 = v9;
                v9[0] = var2_2;
                var0 = String.format("Gradle distribution '%s' does not appear to contain a Gradle distribution.", var0);
                var1_1 /* !! */  = v10;
                v10 = new Install$InstallCheck(null, (String)var0);
            } else {
                var1_1 /* !! */  = v11;
                v11 = new Install$InstallCheck((File)var0, null);
            }
        }
        return var1_1 /* !! */ ;
    }

    /*
     * WARNING - Removed back jump from a try to a catch block - possible behaviour change.
     * Unable to fully structure code
     */
    public static void verifyDownloadChecksum(String var0, File var1_1, String var2_2) {
        block8: {
            if (var2_2 == null) {
                return;
            }
            var3_3 = MessageDigest.getInstance("SHA-256");
            var4_4 = v0;
            v0 = new FileInputStream((File)var1_1);
            try {
                var5_5 = new byte[4096];
lbl8:
                // 2 sources

                while (true) {
                    var6_7 = var4_4.read(var5_5);
                    if (var6_7 <= 0) continue;
                    break;
                }
            }
            catch (Throwable v1) {
                break block8;
            }
            {
                var3_3.update(var5_5, 0, var6_7);
            }
            ** while (var6_7 != -1)
lbl16:
            // 1 sources

            var4_4.close();
            var3_3 = var3_3.digest();
            var4_4 = v2;
            v2 = new StringBuilder();
            for (var5_6 = 0; var5_6 < ((Object)var3_3).length; ++var5_6) {
                var6_8 = Integer.toHexString(var3_3[var5_6] & 255);
                if (var6_8.length() == 1) {
                    var4_4.append('0');
                }
                var4_4.append(var6_8);
            }
            var3_3 = var4_4.toString();
            if (var2_2.equals(var3_3)) {
                return;
            }
            v3 = var1_1;
            v3.delete();
            var1_1 = v3.getAbsolutePath();
            v4 = new Object[4];
            var4_4 = v4;
            v4[0] = var0;
            v4[1] = var1_1;
            v4[2] = var2_2;
            v4[3] = var3_3;
            var0 = String.format("Verification of Gradle distribution failed!%n%nYour Gradle distribution may have been tampered with.%nConfirm that the 'distributionSha256Sum' property in your gradle-wrapper.properties file is correct and you are downloading the wrapper from a trusted source.%n%n Distribution Url: %s%nDownload Location: %s%nExpected checksum: '%s'%n  Actual checksum: '%s'%n", var4_4);
            throw new RuntimeException(var0);
        }
        var4_4.close();
        throw v1;
    }

    public static boolean deleteDir(File file) {
        if (!file.isDirectory()) return file.delete();
        String[] stringArray = file.list();
        if (stringArray == null) return file.delete();
        int n = 0;
        while (n < stringArray.length) {
            if (!Install.deleteDir(new File(file, stringArray[n]))) {
                return false;
            }
            ++n;
        }
        return file.delete();
    }

    /*
     * Exception decompiling
     */
    public static void unzip(File var0, File var1_2) {
        /*
         * This method has failed to decompile.  When submitting a bug report, please provide this stack trace, and (if you hold appropriate legal rights) the relevant class file.
         * 
         * org.benf.cfr.reader.util.ConfusedCFRException: Back jump on a try block [egrp 3[TRYBLOCK] [6 : 69->74)] java.lang.Throwable
         *     at org.benf.cfr.reader.bytecode.analysis.opgraph.Op02WithProcessedDataAndRefs.insertExceptionBlocks(Op02WithProcessedDataAndRefs.java:2283)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:415)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:278)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:201)
         *     at org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:94)
         *     at org.benf.cfr.reader.entities.Method.analyse(Method.java:531)
         *     at org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:1055)
         *     at org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:942)
         *     at org.benf.cfr.reader.Driver.doClass(Driver.java:84)
         *     at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:78)
         *     at the.bytecode.club.bytecodeviewer.decompilers.impl.CFRDecompiler.decompile(CFRDecompiler.java:91)
         *     at the.bytecode.club.bytecodeviewer.decompilers.impl.CFRDecompiler.decompileClassNode(CFRDecompiler.java:74)
         *     at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.processDisplay(BytecodeViewPanelUpdater.java:108)
         *     at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.run(BytecodeViewPanelUpdater.java:159)
         *     at java.base/java.lang.Thread.run(Thread.java:1583)
         */
        throw new IllegalStateException("Decompilation failed");
    }

    public final void unzipLocal(File file, File file2) {
        try {
            Install.unzip(file, file2);
            return;
        }
        catch (IOException iOException) {
            IOException iOException2 = iOException;
            Install install = this;
            install.logger.log("Could not unzip " + file.getAbsolutePath() + " to " + file2.getAbsolutePath() + ".");
            install.logger.log("Reason: " + iOException2.getMessage());
            throw iOException;
        }
    }

    /*
     * Exception decompiling
     */
    public final void forceFetch(File var1_6, URI var2_7) {
        /*
         * This method has failed to decompile.  When submitting a bug report, please provide this stack trace, and (if you hold appropriate legal rights) the relevant class file.
         * 
         * org.benf.cfr.reader.util.ConfusedCFRException: Back jump on a try block [egrp 7[TRYBLOCK] [24 : 355->404)] java.lang.Throwable
         *     at org.benf.cfr.reader.bytecode.analysis.opgraph.Op02WithProcessedDataAndRefs.insertExceptionBlocks(Op02WithProcessedDataAndRefs.java:2283)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisInner(CodeAnalyser.java:415)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysisOrWrapFail(CodeAnalyser.java:278)
         *     at org.benf.cfr.reader.bytecode.CodeAnalyser.getAnalysis(CodeAnalyser.java:201)
         *     at org.benf.cfr.reader.entities.attributes.AttributeCode.analyse(AttributeCode.java:94)
         *     at org.benf.cfr.reader.entities.Method.analyse(Method.java:531)
         *     at org.benf.cfr.reader.entities.ClassFile.analyseMid(ClassFile.java:1055)
         *     at org.benf.cfr.reader.entities.ClassFile.analyseTop(ClassFile.java:942)
         *     at org.benf.cfr.reader.Driver.doClass(Driver.java:84)
         *     at org.benf.cfr.reader.CfrDriverImpl.analyse(CfrDriverImpl.java:78)
         *     at the.bytecode.club.bytecodeviewer.decompilers.impl.CFRDecompiler.decompile(CFRDecompiler.java:91)
         *     at the.bytecode.club.bytecodeviewer.decompilers.impl.CFRDecompiler.decompileClassNode(CFRDecompiler.java:74)
         *     at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.processDisplay(BytecodeViewPanelUpdater.java:108)
         *     at the.bytecode.club.bytecodeviewer.gui.util.BytecodeViewPanelUpdater.run(BytecodeViewPanelUpdater.java:159)
         *     at java.base/java.lang.Thread.run(Thread.java:1583)
         */
        throw new IllegalStateException("Decompilation failed");
    }
}
```

Needless to say: Gradle doesn't obfuscate their stuff

**Comment by micartey** [comment]
My de-compiler played a joke on me and falsely showed obfuscated code while it wasn't...
After checking the checksum and compare it with an official release of gradle I could  confirm that the wrapper jar is indeed official.

Regardless, **using local jars is bad practice** and shall **not** be supported!

Jitpack normally doesn't have those _timeout_ issues and I don't expect them to stay.
Nevertheless, you only need to download it once - afterward, the jar is cached locally.
